apiVersion: batch/v1
kind: Job
metadata:
  name: multi-job
spec:
  completions: 5
  parallelism: 2
  template:
    spec:
      containers:
      - name: pi2
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
